### PR TITLE
Update lunr.min.js

### PR DESCRIPTION
**Pull request by diego898**
This is a quick change to update to the latest `lunr.js` - 2.3.0, addressing https://github.com/hoelzro/tw-full-text-search/issues/6

### CODE REVIEW

**Comment by diego898** [comment]
hey @hoelzro, I added the following line to the comment of the file as well:

`taken from https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.3.0/lunr.min.js`

I just copied and pasted it from there

**Comment by hoelzro** [comment]
Ah, thanks @diego898 - I missed that!  Sorry for the time taken to merge this; it's been a busy week!

**Comment by diego898** [comment]
awesome! Once you release a new version of the plugin based on this version of lunr Id be happy to start testing (no rush)!

**Comment by hoelzro** [comment]
@diego898 Thanks for your patience - I'm going to try to cut a new release tonight!

**Comment by hoelzro** [comment]
Ok, so it turns out that I need to fix `lunr-mutable-indexes` for lunr 2.3 before I can cut a release =(

**Comment by hoelzro** [comment]
Hi @diego898 - thanks for waiting!  I think I managed to iron the issues out; I have released a new version on https://hoelz.ro/files/fts.html.  Would you mind trying it and testing it out?

**Pull request merged**
